routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Route::middleware(['auth'])->group(function () {


    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


    Route::resource('areas', 'AreasController');

    Route::resource('empleados', 'EmpleadosController');
    Route::get('getEmpleado/{id}', 'EmpleadosController@getEmpleado');

    Route::resource('puestos', 'PuestosController');

    Route::resource('rubros', 'RubrosController');

    Route::resource('tipoAvaluos', 'TipoAvaluosController');

    Route::resource('tipoCambios', 'TipoCambioController');

    Route::resource('clientes', 'ClienteController');
    Route::get('getClientes', 'ClienteController@getClientes');
    Route::get('getCliente/{id}', 'ClienteController@getCliente');
    Route::resource('clienteRazonSocials', 'ClienteRazonSocialController');

    Route::resource('servicios', 'ServicioController');

    Route::resource('normas', 'NormasController');

    Route::resource('propositoAvaluos', 'PropositoAvaluoController');


    Route::resource('tipoPlaqueos', 'TipoPlaqueoController');

    Route::resource('cotizacions', 'CotizacionController');


    Route::resource('users', 'UserController');


    Route::resource('cotizacionServicios', 'CotizacionServicioController');

    // Route::post('genera-orden/{id}', [
    //     'as' => 'generaOrden',
    //     'uses' =>'CotizacionController@generaOrden'
    // ]);

    Route::resource('ordenTrabajos', 'OrdenTrabajoController');
    Route::get('asignacion-proyecto', 'OrdenTrabajoController@asignacionProyecto');
    Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::get('genera-orden/{cotizacionId}', 'OrdenTrabajoController@generaOrden');

    Route::get('actualiza-asignacion-empleado/{id}', [
        'as' => 'actualizaAsignacionEmpleado',
        'uses' =>'OrdenTrabajoController@actualizaAsignacionEmpleado'
    ]);

    Route::resource('ordenTrabajoRazonSocials', 'OrdenTrabajoRazonSocialController');

    Route::resource('ordenTrabajoBaseContables', 'OrdenTrabajoBaseContableController');

    Route::post('subir-documento', 'OrdenTrabajoBaseContableController@subirDocumento')->name('subirDocumento');


    Route::get('descargar-plantilla/{id}', 'OrdenTrabajoBaseContableController@descargaPlantilla')->name('descargaPlantilla');
    Route::get('descargar-conteo/{id}', 'OrdenTrabajoConteoController@descargaConteo')->name('descargaConteo');
    Route::get('descargar-cruce/{id}', 'OrdenTrabajoBaseContableController@descargaCruce')->name('descargaCruce');

    Route::get('descargar-repetidos-placa_actual/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaActual')->name('descargaRepetidosPlacaActual');
    Route::get('descargar-repetidos-serie/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosSerie')->name('descargaRepetidosSerie');
    Route::get('descargar-repetidos-placa_anterior/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAnterior')->name('descargaRepetidosPlacaAnterior');

    Route::get('descargar-repetidos-placa_auxiliar_1/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar1')->name('descargaRepetidosPlacaAuxiliar1');
    Route::get('descargar-repetidos-placa_auxiliar_2/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar2')->name('descargaRepetidosPlacaAuxiliar2');

    Route::resource('ordenTrabajoServicios', 'OrdenTrabajoServicioController');
    Route::resource('ordenTrabajoNormas', 'OrdenTrabajoNormaController');
    Route::resource('ordenTrabajoEmpleados', 'OrdenTrabajoEmpleadoController');


    Route::get('avaluos-antecedentes', [
        'as' => 'avaluos-antecedentes',
        'uses' => 'AvaluoController@antecedentes'
    ]);
    Route::post('avaluos-antecedentes-insert', [
        'as' => 'avaluos-antecedentes-insert',
        'uses' => 'AvaluoDetalleController@insert'
    ]);
    Route::get('avaluos-caracteristicas', [
        'as' => 'avaluos-caracteristicas',
        'uses' => 'AvaluoController@caracteristicas'
    ]);
    Route::get('avaluos-terreno', [
        'as' => 'avaluos-terreno',
        'uses' => 'AvaluoController@terreno'
    ]);
    Route::get('avaluos-descripcion', [
        'as' => 'avaluos-descripcion',
        'uses' => 'AvaluoController@descripcion'
    ]);
    Route::get('avaluos-elementos', [
        'as' => 'avaluos-elementos',
        'uses' => 'AvaluoController@elementos'
    ]);
    Route::get('avaluos-conclusiones', [
        'as' => 'avaluos-conclusiones',
        'uses' => 'AvaluoController@conclusiones'
    ]);

    Route::get('descargar-avaluo/{id}', [
        'as' => 'descargar-avaluo',
        'uses' => 'AvaluoController@descargarAvaluo'
    ]);

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoPropositoAvaluos', 'OrdenTrabajoPropositoAvaluoController');

    Route::resource('ordenTrabajoRubroAlcances', 'OrdenTrabajoRubroAlcanceController');

    Route::resource('ordenTrabajoTipoPlaqueos', 'OrdenTrabajoTipoPlaqueoController');

    Route::resource('ordenTrabajoTipoAvaluos', 'OrdenTrabajoTipoAvaluoController');

    Route::resource('ordenTrabajoDocumentos', 'OrdenTrabajoDocumentoController');
    Route::post('subir-archivo', 'OrdenTrabajoDocumentoController@subirArchivo')->name('subirArchivo');
    Route::post('subir-conteo', 'OrdenTrabajoConteoController@subirConteo')->name('subirConteo');
    Route::resource('ordenTrabajoConteos', 'OrdenTrabajoConteoController');

    Route::get('homologar-columnas/{id}', 'OrdenTrabajoBaseContableController@homologarColumnas')->name('homologarColumnas');

    Route::get('obtener-datos-agrupados/{id}/columna/{columna}', [
        'as' => 'obtenerDatosAgrupados',
        'uses' => 'OrdenTrabajoBaseContableController@obtenerDatosAgrupados'
    ]);

    Route::post('reemplaza-datos-por-columna', [
        'as' => 'reemplazaDatosPorColumna',
        'uses' => 'OrdenTrabajoBaseContableController@reemplazaDatosPorColumna'
    ]);

    Route::resource('civils', 'CivilController');
    Route::resource('civil', 'CivilOrdenesController');

    Route::resource('civilDetalles', 'CivilDetalleController');

    Route::resource('avaluos', 'AvaluoController');
    Route::post('subir-avaluo', 'AvaluoController@subirAvaluo')->name('subirAvaluo');

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoBaseContableDetalles', 'OrdenTrabajoBaseContableDetalleController');

    Route::resource('archivoMaestros', 'ArchivoMaestroController');

    Route::get('descargar-archivo-maestro/{id}', [
        'as' => 'descargar-archivo-maestro',
        'uses' => 'ArchivoMaestroController@descargarArchivoMaestro'
    ]);

    Route::get('descargar-sobrante-fisico/{id}', [
        'as' => 'descargar-sobrante-fisico',
        'uses' => 'ArchivoMaestroController@descargarSobranteFisico'
    ]);

    Route::get('descargar-sobrante-contable/{id}', [
        'as' => 'descargar-sobrante-contable',
        'uses' => 'ArchivoMaestroController@descargarSobranteContable'
    ]);

    Route::post('subir-archivo-maestro', 'ArchivoMaestroController@subirArchivoMaestro')->name('subirArchivoMaestro');

    Route::resource('archivoMaestroDetalles', 'ArchivoMaestroDetalleController');

    Route::resource('activoFijos', 'ActivoFijoController');

    Route::resource('conciliacions', 'ConciliacionController');
    Route::post('subir-conciliacion', 'ConciliacionController@subirConciliacion')->name('subirConciliacion');
    Route::resource('conciliacionDetalles', 'ConciliacionDetalleController');

    Route::get('descarga-conciliacion', 'ConciliacionController@getConciliacion');

    Route::get('armado-conciliacion', 'AvaluoController@armadoConciliacion');
    Route::get('armado-avaluo', 'ConciliacionController@armadoAvaluo');
    Route::get('armado-conciliacion-avaluo', 'AvaluoController@armadoConciliacionAvaluo');

    Route::get('factura-armado-conciliacion', 'AvaluoController@facturaArmadoConciliacion');
    Route::get('factura-armado-avaluo', 'AvaluoController@facturaArmadoAvaluo');
    Route::get('factura-armado-conciliacion-avaluo', 'AvaluoController@FacturaArmadoConciliacionAvaluo');

    Route::post('subir-factura-armado-conciliacion', 'AvaluoController@subirFacturaArmadoConciliacion')->name('subirFacturaArmadoConciliacion');
    Route::post('subir-factura-armado-avaluo', 'AvaluoController@subirFacturaArmadoAvaluo')->name('subirFacturaArmadoAvaluo');
    Route::post('subir-factura-armado-conciliacion-avaluo', 'AvaluoController@subirFacturaArmadoConciliacionAvaluo')->name('subirFacturaArmadoConciliacionAvaluo');

    // Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::resource('fichaTecnicas', 'FichaTecnicaController');
    Route::resource('fichaTecnicaDetalles', 'FichaTecnicaDetalleController');

    Route::resource('placas', 'PlacasController');
    Route::resource('cartas', 'CartasController');
    Route::get('actualizar-carta/{id}', 'CartasController@actualizarCarta')->name('actualizarCarta');
    Route::get('download/{nombre}', 'CartasController@download')->name('descarga.archivo');
    Route::resource('reporteador', 'ReporteadorController');
    Route::get('descargar-reporteador', 'ReporteadorController@download')->name('reporteador.download');

app/Models/Avaluo.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use RichanFongdasen\EloquentBlameable\BlameableTrait;

/**
 * Class Avaluo
 * @package App\Models
 * @version April 23, 2020, 10:27 am CDT
 *
 * @property integer orden_trabajo_id
 * @property integer blame_id
 */
class Avaluo extends Model
{
    use SoftDeletes, BlameableTrait;

    public $table = 'avaluos';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected $dates = ['deleted_at'];
    public $with = ['blame', 'ordenTrabajo'];

    public $fillable = [
        'orden_trabajo_id',
        'blame_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'orden_trabajo_id' => 'integer',
        'blame_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'orden_trabajo_id' => 'required'
    ];

    public function blameable()
    {
        return [
            'user' => \App\User::class,
            'createdBy' => 'blame_id',
            'updatedBy' => null,
            'deletedBy' => null
        ];
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function blame()
    {
        return $this->belongsTo(\App\Models\User::class, 'blame_id')->withTrashed();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function ordenTrabajo()
    {
        return $this->belongsTo(\App\Models\OrdenTrabajo::class, 'orden_trabajo_id')->withTrashed();
    }

}

resources/views/avaluos/create.blade.php
@extends('layouts.app')

@section('content')



    @if ( isset(session('flash_notification')[0]))
        @php
            $message = session('flash_notification')[0]
        @endphp

        <div class="alta col-md-12">

            <!--COLLAPSER-->
            <div class="col-xs-12 col-md-12 padding-alta">
                <p class="text-alta centers margin-alta">
                    {!! $message['message'] !!}
                </p>
            </div>
            <br />
            <div class="form-group col-sm-12 col-md-12 col-lg-12 padding-tag margin-traspaso">
                <div class="col-xs-12 col-sm-12 col-md-12 margin-validar center-validar margin-10 centers">

                    <button type="button" onclick="closeFancyboxIframe();"
                    class="btn  btn-default" data-dismiss="modal" aria-label="Close">
                        Cerrar
                    </button>



                </div>
            </div>
            <!--COLLAPSER-->
        </div>

    @else
    <section class="content-header">
        <h1>
            Avaluo
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')

        @if (\Session::has('errores'))
            <div class="alert alert-error">
                <p>Ocurrieron los siguientes errores.</p>
                <ul>
                    @foreach (\Session::get('errores') as $fila => $errores)
                    <br /><li>Fila: {!!$fila !!}
                        @foreach ($errores as $error)
                            <br />{!! $error !!}, <br />
                        @endforeach
                    </li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    <!-- Orden Trabajo Id Field -->
                    <form id="formSubir" name="formSubir" enctype="multipart/form-data" action="{!! route('subirAvaluo') !!}" method="post">
                    <div class="form-group col-sm-6">

                        {!! Form::label('orden_trabajo_id', 'Orden de Trabajo:') !!}
                        {!! Form::select('orden_trabajo_id', $ordenesTrabajo, null, [
                            'class' => 'form-control',
                            'id'=>'orden_trabajo_id',
                            'placeholder' => 'Seleccione...'
                        ])!!}
                    </div>

                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="col-xs-12 col-lg-12 sinpadding2">
                            <div class="custom-upload-file">
                                <input
                                type="file"
                                name="fileImport"
                                id="fileImport"
                                class="inputfile inputfile-transparent"
                                data-multiple-caption="{count} files selected"
                                />
                                <p class="help-block">Seleccione el archivo a subir.</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-lg-12 padding-no">
                            <div class="col-xs-12 col-lg-6 padding-derecho">
                                <input type="submit" class="btn btn-primary">
                                <a href="{!! route('avaluos.index') !!}" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    @endif

@endsection

resources/views/avaluos/datatables_actions.blade.php
{!! Form::open(['route' => ['avaluos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('avaluos.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>

    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('¿Está seguro?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/avaluos/detalle.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '80%']) !!}

@section('js')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection

resources/views/avaluos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Avaluo
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($avaluo, ['route' => ['avaluos.update', $avaluo->id], 'method' => 'patch']) !!}

                        @include('avaluos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/avaluos/fields.blade.php
<!-- Orden Trabajo Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('orden_trabajo_id', 'Orden Trabajo Id:') !!}
    {!! Form::number('orden_trabajo_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Blame Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('blame_id', 'Blame Id:') !!}
    {!! Form::number('blame_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('avaluos.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/avaluos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Avaluos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('avaluos.create') !!}">Agregar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('avaluos.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/avaluos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Avaluo
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('avaluos.show_fields')

                    <a href="{!! route('descargar-avaluo', ['id' => $avaluo->id]) !!}" class="btn btn-primary">Descargar</a>
                    <a href="{!! route('avaluos.index') !!}" class="btn btn-default">Regresar</a>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('avaluos.detalle')
            </div>
        </div>
    </div>
@endsection

resources/views/avaluos/show_fields.blade.php
<!-- Orden Trabajo Id Field -->
<div class="form-group">
    {!! Form::label('orden_trabajo_id', 'Orden Trabajo:') !!}
    <p>{!! $avaluo->ordenTrabajo->num_orden_trabajo !!}</p>
</div>

<!-- Blame Id Field -->
<!-- <div class="form-group">
    {!! Form::label('blame_id', 'Blame Id:') !!}
    <p>{!! $avaluo->blame_id !!}</p>
</div> -->

resources/views/avaluos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection