routes/web.php
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


    Route::resource('areas', 'AreasController');

    Route::resource('empleados', 'EmpleadosController');
    Route::get('getEmpleado/{id}', 'EmpleadosController@getEmpleado');

    Route::resource('puestos', 'PuestosController');

    Route::resource('rubros', 'RubrosController');

    Route::resource('tipoAvaluos', 'TipoAvaluosController');

    Route::resource('tipoCambios', 'TipoCambioController');

    Route::resource('clientes', 'ClienteController');
    Route::get('getClientes', 'ClienteController@getClientes');
    Route::get('getCliente/{id}', 'ClienteController@getCliente');
    Route::resource('clienteRazonSocials', 'ClienteRazonSocialController');

    Route::resource('servicios', 'ServicioController');

    Route::resource('normas', 'NormasController');

    Route::resource('propositoAvaluos', 'PropositoAvaluoController');


    Route::resource('tipoPlaqueos', 'TipoPlaqueoController');

    Route::resource('cotizacions', 'CotizacionController');


    Route::resource('users', 'UserController');


    Route::resource('cotizacionServicios', 'CotizacionServicioController');

    // Route::post('genera-orden/{id}', [
    //     'as' => 'generaOrden',
    //     'uses' =>'CotizacionController@generaOrden'
    // ]);

    Route::resource('ordenTrabajos', 'OrdenTrabajoController');
    Route::get('asignacion-proyecto', 'OrdenTrabajoController@asignacionProyecto');
    Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::get('genera-orden/{cotizacionId}', 'OrdenTrabajoController@generaOrden');

    Route::get('actualiza-asignacion-empleado/{id}', [
        'as' => 'actualizaAsignacionEmpleado',
        'uses' =>'OrdenTrabajoController@actualizaAsignacionEmpleado'
    ]);

    Route::resource('ordenTrabajoRazonSocials', 'OrdenTrabajoRazonSocialController');

    Route::resource('ordenTrabajoBaseContables', 'OrdenTrabajoBaseContableController');

    Route::post('subir-documento', 'OrdenTrabajoBaseContableController@subirDocumento')->name('subirDocumento');


    Route::get('descargar-plantilla/{id}', 'OrdenTrabajoBaseContableController@descargaPlantilla')->name('descargaPlantilla');
    Route::get('descargar-conteo/{id}', 'OrdenTrabajoConteoController@descargaConteo')->name('descargaConteo');
    Route::get('descargar-cruce/{id}', 'OrdenTrabajoBaseContableController@descargaCruce')->name('descargaCruce');

    Route::get('descargar-repetidos-placa_actual/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaActual')->name('descargaRepetidosPlacaActual');
    Route::get('descargar-repetidos-serie/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosSerie')->name('descargaRepetidosSerie');
    Route::get('descargar-repetidos-placa_anterior/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAnterior')->name('descargaRepetidosPlacaAnterior');

    Route::get('descargar-repetidos-placa_auxiliar_1/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar1')->name('descargaRepetidosPlacaAuxiliar1');
    Route::get('descargar-repetidos-placa_auxiliar_2/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar2')->name('descargaRepetidosPlacaAuxiliar2');

    Route::resource('ordenTrabajoServicios', 'OrdenTrabajoServicioController');
    Route::resource('ordenTrabajoNormas', 'OrdenTrabajoNormaController');
    Route::resource('ordenTrabajoEmpleados', 'OrdenTrabajoEmpleadoController');


    Route::get('avaluos-antecedentes', [
        'as' => 'avaluos-antecedentes',
        'uses' => 'AvaluoController@antecedentes'
    ]);
    Route::post('avaluos-antecedentes-insert', [
        'as' => 'avaluos-antecedentes-insert',
        'uses' => 'AvaluoDetalleController@insert'
    ]);
    Route::get('avaluos-caracteristicas', [
        'as' => 'avaluos-caracteristicas',
        'uses' => 'AvaluoController@caracteristicas'
    ]);
    Route::get('avaluos-terreno', [
        'as' => 'avaluos-terreno',
        'uses' => 'AvaluoController@terreno'
    ]);
    Route::get('avaluos-descripcion', [
        'as' => 'avaluos-descripcion',
        'uses' => 'AvaluoController@descripcion'
    ]);
    Route::get('avaluos-elementos', [
        'as' => 'avaluos-elementos',
        'uses' => 'AvaluoController@elementos'
    ]);
    Route::get('avaluos-conclusiones', [
        'as' => 'avaluos-conclusiones',
        'uses' => 'AvaluoController@conclusiones'
    ]);

    Route::get('descargar-avaluo/{id}', [
        'as' => 'descargar-avaluo',
        'uses' => 'AvaluoController@descargarAvaluo'
    ]);

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoPropositoAvaluos', 'OrdenTrabajoPropositoAvaluoController');

    Route::resource('ordenTrabajoRubroAlcances', 'OrdenTrabajoRubroAlcanceController');

    Route::resource('ordenTrabajoTipoPlaqueos', 'OrdenTrabajoTipoPlaqueoController');

    Route::resource('ordenTrabajoTipoAvaluos', 'OrdenTrabajoTipoAvaluoController');

    Route::resource('ordenTrabajoDocumentos', 'OrdenTrabajoDocumentoController');
    Route::post('subir-archivo', 'OrdenTrabajoDocumentoController@subirArchivo')->name('subirArchivo');
    Route::post('subir-conteo', 'OrdenTrabajoConteoController@subirConteo')->name('subirConteo');
    Route::resource('ordenTrabajoConteos', 'OrdenTrabajoConteoController');

    Route::get('homologar-columnas/{id}', 'OrdenTrabajoBaseContableController@homologarColumnas')->name('homologarColumnas');

    Route::get('obtener-datos-agrupados/{id}/columna/{columna}', [
        'as' => 'obtenerDatosAgrupados',
        'uses' => 'OrdenTrabajoBaseContableController@obtenerDatosAgrupados'
    ]);

    Route::post('reemplaza-datos-por-columna', [
        'as' => 'reemplazaDatosPorColumna',
        'uses' => 'OrdenTrabajoBaseContableController@reemplazaDatosPorColumna'
    ]);

    Route::resource('civils', 'CivilController');
    Route::resource('civil', 'CivilOrdenesController');

    Route::resource('civilDetalles', 'CivilDetalleController');

    Route::resource('avaluos', 'AvaluoController');
    Route::post('subir-avaluo', 'AvaluoController@subirAvaluo')->name('subirAvaluo');

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoBaseContableDetalles', 'OrdenTrabajoBaseContableDetalleController');

    Route::resource('archivoMaestros', 'ArchivoMaestroController');

    Route::get('descargar-archivo-maestro/{id}', [
        'as' => 'descargar-archivo-maestro',
        'uses' => 'ArchivoMaestroController@descargarArchivoMaestro'
    ]);

    Route::get('descargar-sobrante-fisico/{id}', [
        'as' => 'descargar-sobrante-fisico',
        'uses' => 'ArchivoMaestroController@descargarSobranteFisico'
    ]);

    Route::get('descargar-sobrante-contable/{id}', [
        'as' => 'descargar-sobrante-contable',
        'uses' => 'ArchivoMaestroController@descargarSobranteContable'
    ]);

    Route::post('subir-archivo-maestro', 'ArchivoMaestroController@subirArchivoMaestro')->name('subirArchivoMaestro');

    Route::resource('archivoMaestroDetalles', 'ArchivoMaestroDetalleController');

    Route::resource('activoFijos', 'ActivoFijoController');

    Route::resource('conciliacions', 'ConciliacionController');
    Route::post('subir-conciliacion', 'ConciliacionController@subirConciliacion')->name('subirConciliacion');
    Route::resource('conciliacionDetalles', 'ConciliacionDetalleController');

    Route::get('descarga-conciliacion', 'ConciliacionController@getConciliacion');

    Route::get('armado-conciliacion', 'AvaluoController@armadoConciliacion');
    Route::get('armado-avaluo', 'ConciliacionController@armadoAvaluo');
    Route::get('armado-conciliacion-avaluo', 'AvaluoController@armadoConciliacionAvaluo');

    Route::get('factura-armado-conciliacion', 'AvaluoController@facturaArmadoConciliacion');
    Route::get('factura-armado-avaluo', 'AvaluoController@facturaArmadoAvaluo');
    Route::get('factura-armado-conciliacion-avaluo', 'AvaluoController@FacturaArmadoConciliacionAvaluo');

    Route::post('subir-factura-armado-conciliacion', 'AvaluoController@subirFacturaArmadoConciliacion')->name('subirFacturaArmadoConciliacion');
    Route::post('subir-factura-armado-avaluo', 'AvaluoController@subirFacturaArmadoAvaluo')->name('subirFacturaArmadoAvaluo');
    Route::post('subir-factura-armado-conciliacion-avaluo', 'AvaluoController@subirFacturaArmadoConciliacionAvaluo')->name('subirFacturaArmadoConciliacionAvaluo');

    // Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::resource('fichaTecnicas', 'FichaTecnicaController');
    Route::resource('fichaTecnicaDetalles', 'FichaTecnicaDetalleController');

    Route::resource('placas', 'PlacasController');
    Route::resource('cartas', 'CartasController');
    Route::get('actualizar-carta/{id}', 'CartasController@actualizarCarta')->name('actualizarCarta');
    Route::get('download/{nombre}', 'CartasController@download')->name('descarga.archivo');
    Route::resource('reporteador', 'ReporteadorController');
    Route::get('descargar-reporteador', 'ReporteadorController@download')->name('reporteador.download');
    Route::resource('cuadernillo', 'CuadernilloController');
    Route::get('portada', 'CuadernilloController@portada')->name('cuadernillo.portada');
    Route::get('crear-contenido', 'CuadernilloController@contenidoCrear')->name('cuadernillo.contenido.crear');
    Route::get('crear-contenido-indice', 'CuadernilloController@contenidoCrearIndice')->name('cuadernillo.indice.crear');
    Route::post('crear-indice', 'CuadernilloController@crearIndice')->name('indice.crear');
    Route::get('crear-separador', 'CuadernilloController@separador')->name('cuadernillo.separador');
    

    Route::get('catalogo/{id}', 'CatalogoController@create')->name('catalogo.crear');
});

app/Http/Controllers/AvaluoDetalleController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\AvaluoDetalleDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateAvaluoDetalleRequest;
use App\Http\Requests\UpdateAvaluoDetalleRequest;
use App\Repositories\AvaluoDetalleRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class AvaluoDetalleController extends AppBaseController
{
    /** @var  AvaluoDetalleRepository */
    private $avaluoDetalleRepository;

    public function __construct(AvaluoDetalleRepository $avaluoDetalleRepo)
    {
        $this->avaluoDetalleRepository = $avaluoDetalleRepo;
    }

    /**
     * Display a listing of the AvaluoDetalle.
     *
     * @param AvaluoDetalleDataTable $avaluoDetalleDataTable
     * @return Response
     */
    public function index(AvaluoDetalleDataTable $avaluoDetalleDataTable)
    {
        return $avaluoDetalleDataTable->render('avaluo_detalles.index');
    }

    /**
     * Show the form for creating a new AvaluoDetalle.
     *
     * @return Response
     */
    public function create()
    {
        return view('avaluo_detalles.create');
    }

    /**
     * Store a newly created AvaluoDetalle in storage.
     *
     * @param CreateAvaluoDetalleRequest $request
     *
     * @return Response
     */
    public function store(CreateAvaluoDetalleRequest $request)
    {
        $input = $request->all();

        $avaluoDetalle = $this->avaluoDetalleRepository->create($input);

        Flash::success('Avaluo Detalle saved successfully.');

        return redirect(route('avaluoDetalles.index'));
    }

    /**
     * Display the specified AvaluoDetalle.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $avaluoDetalle = $this->avaluoDetalleRepository->find($id);

        if (empty($avaluoDetalle)) {
            Flash::error('Avaluo Detalle not found');

            return redirect(route('avaluoDetalles.index'));
        }

        return view('avaluo_detalles.show')->with('avaluoDetalle', $avaluoDetalle);
    }

    /**
     * Show the form for editing the specified AvaluoDetalle.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $avaluoDetalle = $this->avaluoDetalleRepository->find($id);

        if (empty($avaluoDetalle)) {
            Flash::error('Avaluo Detalle not found');

            return redirect(route('avaluoDetalles.index'));
        }

        return view('avaluo_detalles.edit')->with('avaluoDetalle', $avaluoDetalle);
    }

    /**
     * Update the specified AvaluoDetalle in storage.
     *
     * @param  int              $id
     * @param UpdateAvaluoDetalleRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAvaluoDetalleRequest $request)
    {
        $avaluoDetalle = $this->avaluoDetalleRepository->find($id);

        if (empty($avaluoDetalle)) {
            Flash::error('Avaluo Detalle not found');

            return redirect(route('avaluoDetalles.index'));
        }

        $avaluoDetalle = $this->avaluoDetalleRepository->update($request->all(), $id);

        Flash::success('Avaluo Detalle updated successfully.');

        return redirect(route('avaluoDetalles.index'));
    }

    /**
     * Remove the specified AvaluoDetalle from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $avaluoDetalle = $this->avaluoDetalleRepository->find($id);

        if (empty($avaluoDetalle)) {
            Flash::error('Avaluo Detalle not found');

            return redirect(route('avaluoDetalles.index'));
        }

        $this->avaluoDetalleRepository->delete($id);

        Flash::success('Avaluo Detalle deleted successfully.');

        return redirect(route('avaluoDetalles.index'));
    }
}

resources/views/avaluo_detalles/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Avaluo Detalle
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'avaluoDetalles.store']) !!}

                        @include('avaluo_detalles.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/avaluo_detalles/datatables_actions.blade.php
{!! Form::open(['route' => ['avaluoDetalles.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('avaluoDetalles.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('avaluoDetalles.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/avaluo_detalles/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Avaluo Detalle
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($avaluoDetalle, ['route' => ['avaluoDetalles.update', $avaluoDetalle->id], 'method' => 'patch']) !!}

                        @include('avaluo_detalles.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/avaluo_detalles/fields.blade.php
<!-- Avaluo Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('avaluo_id', 'Avaluo Id:') !!}
    {!! Form::number('avaluo_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Asset Field -->
<div class="form-group col-sm-6">
    {!! Form::label('asset', 'Asset:') !!}
    {!! Form::text('asset', null, ['class' => 'form-control']) !!}
</div>

<!-- Rubro Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rubro', 'Rubro:') !!}
    {!! Form::text('rubro', null, ['class' => 'form-control']) !!}
</div>

<!-- Desglose Field -->
<div class="form-group col-sm-6">
    {!! Form::label('desglose', 'Desglose:') !!}
    {!! Form::text('desglose', null, ['class' => 'form-control']) !!}
</div>

<!-- Asset Descripcion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('asset_descripcion', 'Asset Descripcion:') !!}
    {!! Form::text('asset_descripcion', null, ['class' => 'form-control']) !!}
</div>

<!-- Acquis Val Field -->
<div class="form-group col-sm-6">
    {!! Form::label('acquis_val', 'Acquis Val:') !!}
    {!! Form::number('acquis_val', null, ['class' => 'form-control']) !!}
</div>

<!-- Accum Dep Field -->
<div class="form-group col-sm-6">
    {!! Form::label('accum_dep', 'Accum Dep:') !!}
    {!! Form::number('accum_dep', null, ['class' => 'form-control']) !!}
</div>

<!-- Book Val Field -->
<div class="form-group col-sm-6">
    {!! Form::label('book_val', 'Book Val:') !!}
    {!! Form::number('book_val', null, ['class' => 'form-control']) !!}
</div>

<!-- Placa Anterior Homogenea Field -->
<div class="form-group col-sm-6">
    {!! Form::label('placa_anterior_homogenea', 'Placa Anterior Homogenea:') !!}
    {!! Form::text('placa_anterior_homogenea', null, ['class' => 'form-control']) !!}
</div>

<!-- Placa Anterior Field -->
<div class="form-group col-sm-6">
    {!! Form::label('placa_anterior', 'Placa Anterior:') !!}
    {!! Form::text('placa_anterior', null, ['class' => 'form-control']) !!}
</div>

<!-- Edificio Field -->
<div class="form-group col-sm-6">
    {!! Form::label('edificio', 'Edificio:') !!}
    {!! Form::text('edificio', null, ['class' => 'form-control']) !!}
</div>

<!-- Piso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('piso', 'Piso:') !!}
    {!! Form::text('piso', null, ['class' => 'form-control']) !!}
</div>

<!-- Rubro Vegsa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rubro_vegsa', 'Rubro Vegsa:') !!}
    {!! Form::text('rubro_vegsa', null, ['class' => 'form-control']) !!}
</div>

<!-- Catalogo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('catalogo', 'Catalogo:') !!}
    {!! Form::text('catalogo', null, ['class' => 'form-control']) !!}
</div>

<!-- Descripcion Vegsa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descripcion_vegsa', 'Descripcion Vegsa:') !!}
    {!! Form::text('descripcion_vegsa', null, ['class' => 'form-control']) !!}
</div>

<!-- Marca Field -->
<div class="form-group col-sm-6">
    {!! Form::label('marca', 'Marca:') !!}
    {!! Form::text('marca', null, ['class' => 'form-control']) !!}
</div>

<!-- Modelo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('modelo', 'Modelo:') !!}
    {!! Form::text('modelo', null, ['class' => 'form-control']) !!}
</div>

<!-- Serie Field -->
<div class="form-group col-sm-6">
    {!! Form::label('serie', 'Serie:') !!}
    {!! Form::text('serie', null, ['class' => 'form-control']) !!}
</div>

<!-- Area Field -->
<div class="form-group col-sm-6">
    {!! Form::label('area', 'Area:') !!}
    {!! Form::text('area', null, ['class' => 'form-control']) !!}
</div>

<!-- Localidad Field -->
<div class="form-group col-sm-6">
    {!! Form::label('localidad', 'Localidad:') !!}
    {!! Form::text('localidad', null, ['class' => 'form-control']) !!}
</div>

<!-- Vrn Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vrn', 'Vrn:') !!}
    {!! Form::number('vrn', null, ['class' => 'form-control']) !!}
</div>

<!-- Porcentaje Dep Field -->
<div class="form-group col-sm-6">
    {!! Form::label('porcentaje_dep', 'Porcentaje Dep:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('porcentaje_dep', 0) !!}
        {!! Form::checkbox('porcentaje_dep', '1', null) !!}
    </label>
</div>


<!-- Dep Acum Field -->
<div class="form-group col-sm-6">
    {!! Form::label('dep_acum', 'Dep Acum:') !!}
    {!! Form::number('dep_acum', null, ['class' => 'form-control']) !!}
</div>

<!-- Vnr Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vnr', 'Vnr:') !!}
    {!! Form::number('vnr', null, ['class' => 'form-control']) !!}
</div>

<!-- Vur Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vur', 'Vur:') !!}
    {!! Form::number('vur', null, ['class' => 'form-control']) !!}
</div>

<!-- Da Field -->
<div class="form-group col-sm-6">
    {!! Form::label('da', 'Da:') !!}
    {!! Form::number('da', null, ['class' => 'form-control']) !!}
</div>

<!-- Vut Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vut', 'Vut:') !!}
    {!! Form::number('vut', null, ['class' => 'form-control']) !!}
</div>

<!-- Blame Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('blame_id', 'Blame Id:') !!}
    {!! Form::number('blame_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('avaluoDetalles.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/avaluo_detalles/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Avaluo Detalles</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('avaluoDetalles.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('avaluo_detalles.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/avaluo_detalles/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Avaluo Detalle
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('avaluo_detalles.show_fields')
                    <a href="{!! route('avaluoDetalles.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/avaluo_detalles/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection