routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Route::middleware(['auth'])->group(function () {


    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


    Route::resource('areas', 'AreasController');

    Route::resource('empleados', 'EmpleadosController');
    Route::get('getEmpleado/{id}', 'EmpleadosController@getEmpleado');

    Route::resource('puestos', 'PuestosController');

    Route::resource('rubros', 'RubrosController');

    Route::resource('tipoAvaluos', 'TipoAvaluosController');

    Route::resource('tipoCambios', 'TipoCambioController');

    Route::resource('clientes', 'ClienteController');
    Route::get('getClientes', 'ClienteController@getClientes');
    Route::get('getCliente/{id}', 'ClienteController@getCliente');
    Route::resource('clienteRazonSocials', 'ClienteRazonSocialController');

    Route::resource('servicios', 'ServicioController');

    Route::resource('normas', 'NormasController');

    Route::resource('propositoAvaluos', 'PropositoAvaluoController');


    Route::resource('tipoPlaqueos', 'TipoPlaqueoController');

    Route::resource('cotizacions', 'CotizacionController');


    Route::resource('users', 'UserController');


    Route::resource('cotizacionServicios', 'CotizacionServicioController');

    // Route::post('genera-orden/{id}', [
    //     'as' => 'generaOrden',
    //     'uses' =>'CotizacionController@generaOrden'
    // ]);

    Route::resource('ordenTrabajos', 'OrdenTrabajoController');
    Route::get('asignacion-proyecto', 'OrdenTrabajoController@asignacionProyecto');
    Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::get('genera-orden/{cotizacionId}', 'OrdenTrabajoController@generaOrden');

    Route::get('actualiza-asignacion-empleado/{id}', [
        'as' => 'actualizaAsignacionEmpleado',
        'uses' =>'OrdenTrabajoController@actualizaAsignacionEmpleado'
    ]);

    Route::resource('ordenTrabajoRazonSocials', 'OrdenTrabajoRazonSocialController');

    Route::resource('ordenTrabajoBaseContables', 'OrdenTrabajoBaseContableController');

    Route::post('subir-documento', 'OrdenTrabajoBaseContableController@subirDocumento')->name('subirDocumento');


    Route::get('descargar-plantilla/{id}', 'OrdenTrabajoBaseContableController@descargaPlantilla')->name('descargaPlantilla');
    Route::get('descargar-conteo/{id}', 'OrdenTrabajoConteoController@descargaConteo')->name('descargaConteo');
    Route::get('descargar-cruce/{id}', 'OrdenTrabajoBaseContableController@descargaCruce')->name('descargaCruce');

    Route::get('descargar-repetidos-placa_actual/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaActual')->name('descargaRepetidosPlacaActual');
    Route::get('descargar-repetidos-serie/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosSerie')->name('descargaRepetidosSerie');
    Route::get('descargar-repetidos-placa_anterior/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAnterior')->name('descargaRepetidosPlacaAnterior');

    Route::get('descargar-repetidos-placa_auxiliar_1/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar1')->name('descargaRepetidosPlacaAuxiliar1');
    Route::get('descargar-repetidos-placa_auxiliar_2/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar2')->name('descargaRepetidosPlacaAuxiliar2');

    Route::resource('ordenTrabajoServicios', 'OrdenTrabajoServicioController');
    Route::resource('ordenTrabajoNormas', 'OrdenTrabajoNormaController');
    Route::resource('ordenTrabajoEmpleados', 'OrdenTrabajoEmpleadoController');


    Route::get('avaluos-antecedentes', [
        'as' => 'avaluos-antecedentes',
        'uses' => 'AvaluoController@antecedentes'
    ]);
    Route::post('avaluos-antecedentes-insert', [
        'as' => 'avaluos-antecedentes-insert',
        'uses' => 'AvaluoDetalleController@insert'
    ]);
    Route::get('avaluos-caracteristicas', [
        'as' => 'avaluos-caracteristicas',
        'uses' => 'AvaluoController@caracteristicas'
    ]);
    Route::get('avaluos-terreno', [
        'as' => 'avaluos-terreno',
        'uses' => 'AvaluoController@terreno'
    ]);
    Route::get('avaluos-descripcion', [
        'as' => 'avaluos-descripcion',
        'uses' => 'AvaluoController@descripcion'
    ]);
    Route::get('avaluos-elementos', [
        'as' => 'avaluos-elementos',
        'uses' => 'AvaluoController@elementos'
    ]);
    Route::get('avaluos-conclusiones', [
        'as' => 'avaluos-conclusiones',
        'uses' => 'AvaluoController@conclusiones'
    ]);

    Route::get('descargar-avaluo/{id}', [
        'as' => 'descargar-avaluo',
        'uses' => 'AvaluoController@descargarAvaluo'
    ]);

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoPropositoAvaluos', 'OrdenTrabajoPropositoAvaluoController');

    Route::resource('ordenTrabajoRubroAlcances', 'OrdenTrabajoRubroAlcanceController');

    Route::resource('ordenTrabajoTipoPlaqueos', 'OrdenTrabajoTipoPlaqueoController');

    Route::resource('ordenTrabajoTipoAvaluos', 'OrdenTrabajoTipoAvaluoController');

    Route::resource('ordenTrabajoDocumentos', 'OrdenTrabajoDocumentoController');
    Route::post('subir-archivo', 'OrdenTrabajoDocumentoController@subirArchivo')->name('subirArchivo');
    Route::post('subir-conteo', 'OrdenTrabajoConteoController@subirConteo')->name('subirConteo');
    Route::resource('ordenTrabajoConteos', 'OrdenTrabajoConteoController');

    Route::get('homologar-columnas/{id}', 'OrdenTrabajoBaseContableController@homologarColumnas')->name('homologarColumnas');

    Route::get('obtener-datos-agrupados/{id}/columna/{columna}', [
        'as' => 'obtenerDatosAgrupados',
        'uses' => 'OrdenTrabajoBaseContableController@obtenerDatosAgrupados'
    ]);

    Route::post('reemplaza-datos-por-columna', [
        'as' => 'reemplazaDatosPorColumna',
        'uses' => 'OrdenTrabajoBaseContableController@reemplazaDatosPorColumna'
    ]);

    Route::resource('civils', 'CivilController');
    Route::resource('civil', 'CivilOrdenesController');

    Route::resource('civilDetalles', 'CivilDetalleController');

    Route::resource('avaluos', 'AvaluoController');
    Route::post('subir-avaluo', 'AvaluoController@subirAvaluo')->name('subirAvaluo');

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoBaseContableDetalles', 'OrdenTrabajoBaseContableDetalleController');

    Route::resource('archivoMaestros', 'ArchivoMaestroController');

    Route::get('descargar-archivo-maestro/{id}', [
        'as' => 'descargar-archivo-maestro',
        'uses' => 'ArchivoMaestroController@descargarArchivoMaestro'
    ]);

    Route::get('descargar-sobrante-fisico/{id}', [
        'as' => 'descargar-sobrante-fisico',
        'uses' => 'ArchivoMaestroController@descargarSobranteFisico'
    ]);

    Route::get('descargar-sobrante-contable/{id}', [
        'as' => 'descargar-sobrante-contable',
        'uses' => 'ArchivoMaestroController@descargarSobranteContable'
    ]);

    Route::post('subir-archivo-maestro', 'ArchivoMaestroController@subirArchivoMaestro')->name('subirArchivoMaestro');

    Route::resource('archivoMaestroDetalles', 'ArchivoMaestroDetalleController');

    Route::resource('activoFijos', 'ActivoFijoController');

    Route::resource('conciliacions', 'ConciliacionController');
    Route::post('subir-conciliacion', 'ConciliacionController@subirConciliacion')->name('subirConciliacion');
    Route::resource('conciliacionDetalles', 'ConciliacionDetalleController');

    Route::get('descarga-conciliacion', 'ConciliacionController@getConciliacion');

    Route::get('armado-conciliacion', 'AvaluoController@armadoConciliacion');
    Route::get('armado-avaluo', 'ConciliacionController@armadoAvaluo');
    Route::get('armado-conciliacion-avaluo', 'AvaluoController@armadoConciliacionAvaluo');

    Route::get('factura-armado-conciliacion', 'AvaluoController@facturaArmadoConciliacion');
    Route::get('factura-armado-avaluo', 'AvaluoController@facturaArmadoAvaluo');
    Route::get('factura-armado-conciliacion-avaluo', 'AvaluoController@FacturaArmadoConciliacionAvaluo');

    Route::post('subir-factura-armado-conciliacion', 'AvaluoController@subirFacturaArmadoConciliacion')->name('subirFacturaArmadoConciliacion');
    Route::post('subir-factura-armado-avaluo', 'AvaluoController@subirFacturaArmadoAvaluo')->name('subirFacturaArmadoAvaluo');
    Route::post('subir-factura-armado-conciliacion-avaluo', 'AvaluoController@subirFacturaArmadoConciliacionAvaluo')->name('subirFacturaArmadoConciliacionAvaluo');

    // Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::resource('fichaTecnicas', 'FichaTecnicaController');
    Route::resource('fichaTecnicaDetalles', 'FichaTecnicaDetalleController');

    Route::resource('placas', 'PlacasController');
    Route::resource('cartas', 'CartasController');
    Route::get('actualizar-carta/{id}', 'CartasController@actualizarCarta')->name('actualizarCarta');
    Route::get('download/{nombre}', 'CartasController@download')->name('descarga.archivo');
    Route::resource('reporteador', 'ReporteadorController');
    Route::get('descargar-reporteador', 'ReporteadorController@download')->name('reporteador.download');

resources/views/orden_trabajo_base_contables/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden Trabajo Base Contable
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    <!-- Orden Trabajo Id Field -->
                    <form id="formSubir" name="formSubir" enctype="multipart/form-data" action="{!! route('subirDocumento') !!}" method="post">
                    <div class="form-group col-sm-6">

                        {!! Form::label('orden_trabajo_id', 'Orden de Trabajo:') !!}
                        {!! Form::select('orden_trabajo_id', $ordenesTrabajo, null, [
                            'class' => 'form-control',
                            'id'=>'orden_trabajo_id',
                            'placeholder' => 'Seleccione...'
                        ])!!}
                    </div>

                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="col-xs-12 col-lg-12 sinpadding2">
                            <div class="custom-upload-file">
                                <input
                                type="file"
                                name="fileImport"
                                id="fileImport"
                                class="inputfile inputfile-transparent"
                                data-multiple-caption="{count} files selected"
                                />
                                <p class="help-block">Seleccione el archivo a subir.</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-lg-12 padding-no">
                            <div class="col-xs-12 col-lg-6 padding-derecho">
                                <input type="submit" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
@endsection

resources/views/orden_trabajo_base_contables/datatables_actions.blade.php
{!! Form::open(['route' => ['ordenTrabajoBaseContables.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('ordenTrabajoBaseContables.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('¿Está seguro?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/orden_trabajo_base_contables/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden Trabajo Base Contable
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ordenTrabajoBaseContable, ['route' => ['ordenTrabajoBaseContables.update', $ordenTrabajoBaseContable->id], 'method' => 'patch']) !!}

                        @include('orden_trabajo_base_contables.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/orden_trabajo_base_contables/fields.blade.php
<!-- Orden Trabajo Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('orden_trabajo_id', 'Orden Trabajo Id:') !!}
    {!! Form::number('orden_trabajo_id', null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ordenTrabajoBaseContables.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/orden_trabajo_base_contables/homologar-columnas.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Homologar Columnas - {{$ordenTrabajoBaseContable->nombre}}
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" id="base_contable_1">
                    <div class="col-md-12" style="overflow:auto;">
                        <br />
                        <input type="hidden" id="orden_trabajo_base_contable_id" name="orden_trabajo_base_contable_id" value="{{$ordenTrabajoBaseContable->id}}">
                        <input type="hidden" id="public_url" name="public_url" value="{{url('/')}}">
                        <input type="hidden" id="csrf-token" name="csrf-token" value="{{ csrf_token() }}">
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                <?php
                                // dd(json_decode($ordenTrabajoBaseContable->json_cabeceras));
                                    $aEncabezado = array_filter(json_decode($ordenTrabajoBaseContable->json_cabeceras, true));
                                    $nofilas = count($aEncabezado);
                                    $contador = 0;

// dd(url()->current(), url()->full(), Illuminate\Support\Facades\URL::current(), url('/'));
                                    foreach ($aEncabezado as $clave => $valor) {
                                        $contador++;

                                        ?>
                                        <div class="panel panel-default">
                                          <div class="panel-heading" role="tab" id="heading_{{$contador}}">
                                            <h4 class="panel-title">
                                              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_{{$contador}}" aria-expanded="true" aria-controls="collapse_{{$contador}}">
                                                {{$valor}}
                                              </a>
                                            </h4>
                                          </div>
                                          <div
                                              id="collapse_{{$contador}}"
                                              data-contador="{{$contador}}"
                                              data-columna="{{$valor}}"
                                              class="panel-collapse collapse "
                                              role="tabpanel"
                                              aria-labelledby="heading_{{$contador}}"
                                          >
                                            <div class="panel-body" id="panel-body-{{$contador}}">
                                                <form method="POST" action="{{route('reemplazaDatosPorColumna')}}" id="form-{{$contador}}"><br /></form>
                                            </div>
                                          </div>
                                        </div>
                                        <?php
                                    }
                                ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
@endsection


@section('scripts')

    <script type="text/javascript">

        $(function() {

            $(".collapse").on('shown.bs.collapse', function(e) {

                var contador = $(this).data('contador');
                var columna = $(this).data('columna');

                var divId = this.id;
                var orden_trabajo_base_contable_id = $('#orden_trabajo_base_contable_id').val();
                var url = $('#public_url').val() + '/obtener-datos-agrupados/' +
                + orden_trabajo_base_contable_id+'/'
                + 'columna/' + columna
                console.log(url);

                if ($(this).is(e.target)) {

                    blockDiv(this.id);

                    $.getJSON(url, function(data) {
                        console.log(data)
                        var items = [];
                        var selectReemplazar = 'Reemplazar registros seleccionados por: <br /> <select name="valor">';
                        selectReemplazar += "<option value='' >Seleccione... </option>";

                        $( "#" + 'form-'+contador ).empty();

                          $.each( data, function( key, val ) {
                            items.push( " <input type='checkbox' id ='chk-" + key + "' name='registros[]' value='"+val+"'>"
                            + " <label for='chk-" + key + "'>" + val + "</label>" );

                            selectReemplazar += "<option value='"+val+"' >"+val+" </option>";

                          });

                          selectReemplazar += "</select>";
                          selectReemplazar += " &nbsp; <input type='submit' value='Aceptar'></p>";

                          items.sort((a,b)=>a-b);
                          console.log(items.sort((a,b)=>a-b));

                          $( items.join( "<br />" )).appendTo( "#" + 'form-'+contador );
                          $( "#" + 'form-'+contador ).append('<br />' + selectReemplazar);

                        unblockDiv(divId)
                        console.log(divId)
                    });

                }

                return ;

            });

            $(".collapse").on('hide.bs.collapse', function(e) {

                var contador = $(this).data('contador');
                if ($(this).is(e.target)) {

                    $('#loader_' + contador).hide();

                    unblockDiv(this.id)
                    $( "#" + 'form-'+contador ).empty().append('<br />');
                }

            });

        });

        // https://programandoointentandolo.com/2017/12/comprobar-elemento-esta-visible-jquery.html

        // Si elemento esta visible lo oculta y si no lo muestra

        // if ($('#elemento').is(':visible')) {
        //     $('#elemento').hide();
        // } else {
        //     $('#elemento').show();
        // }
        //
        // // Si el elemento2 esta oculto lo indica por consola y si no ejecuta una funcion
        // if ($('#elemento2').is(':hidden')) {
        //     console.log("Esta oculto");
        // } else {
        //     hacerAlgo();
        // }

    $(document).ready(function() {


        // $('#blockButton').click(function() {
        //     $('div.test').block({ message: null });
        // });
        //
        // $('#blockButton2').click(function() {
        //     $('div.test').block({
        //         message: '<h1>Processing</h1>',
        //         css: { border: '3px solid #a00' }
        //     });
        // });
        //
        // $('#unblockButton').click(function() {
        //     $('div.test').unblock();
        // });
        //
        // $('a.test').click(function() {
        //     alert('link clicked');
        //     return false;
        // });
        //
        // $('#collapse_1').block({
        //     message: '<h5>Cargando <img src="http://localhost/vegsa/public/images/ajax-loader.gif"></h5>',
        //     css: { border: '1px solid #666' }
        // });
        //
        // $('#collapse_1').unblock();

    });


    function blockDiv(id){
        // $('#' + id).block();
        $('#' + id).block({
            message: '<h5>Cargando &nbsp; <img src="{{ asset('images/clasic-loader.gif') }}"></h5>',
            css: { border: '1px solid #666' }
        });

        return ;
    }

    function unblockDiv(id){
        $('#' + id).unblock();

        return ;
    }

    // $.ajaxSetup({
    //     headers: {
    //         'X-CSRF-TOKEN': $('#csrf-token').val()
    //     }
    // });

    $(document).on("submit", "form", function(event)
    {
        event.preventDefault();

        console.log('envia formulario');

        var formData = new FormData(this); // use serializeArray
        var formId = this.id;
        var divCollapse = $(this).parent("div").parent("div").attr('id');

        console.log(formData);
        console.log(divCollapse);
        // return ;
        formData.append('nombre_columna', $(this).parent("div").parent("div").data('columna'));
        formData.append('orden_trabajo_base_contable_id', $('#orden_trabajo_base_contable_id').val());
        // formData.append('nombre_columna', $('#orden_trabajo_base_contable_id').val());

        $.ajax({
            url: $(this).attr("action"),
            type: $(this).attr("method"),
            headers: {
                'X-CSRF-TOKEN': $('#csrf-token').val()
            },
            // type: $(this).attr("method"),
            dataType: "JSON",
            data: formData,
            beforeSend: function(){
                blockDiv(divCollapse);
            },
            processData: false,
            contentType: false,
            success: function (data, status){
                unblockDiv(divCollapse);
                // $('#' + divCollapse).collapse('hide');
                $('#' + divCollapse).collapse('toggle');
                // $('#' + divCollapse).collapse('show');
            },
            error: function (xhr, desc, err){
                unblockDiv(divCollapse);

            }
        })
        .done(function (resul) {
            unblockDiv(divCollapse);
        });
    });
</script>

@append

resources/views/orden_trabajo_base_contables/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Inventario</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('ordenTrabajoBaseContables.create') !!}">Agregar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('orden_trabajo_base_contables.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/orden_trabajo_base_contables/show.blade.php
@extends('layouts.app')
@include('partials.custom_datatable.datatable')
@section('content')
    <section class="content-header">
        <h1>
            Inventario
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <br />
                        <table id="tbl_razon_social" class="table table-hover table-bordered"  style="width:100%">
                            <thead>
                                <tr style="background-color: #f9f9f9">
                                    <th>Archivo</th>
                                    <th>Servidor</th>
                                    <th>Base de datos</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $contador = 0 ?>
                                @foreach ($basesContables as $registro)
                                <?php $contador++ ?>
                                <tr  class="text-center">
                                    <td>{{ $registro->nombre}}</td>
                                    <td><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i></td>
                                    <td><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        @includeWhen(count($plantas) == 0, 'orden_trabajo_base_contables.detalles.conteo', [
            'conteo' => $conteo
        ])

        @includeWhen(count($plantas) > 0, 'orden_trabajo_base_contables.detalles.conteo-planta', [
            'conteo' => $conteo
        ])

        <div class="clearfix"></div>
        @include('orden_trabajo_base_contables.detalles.componetizacion')
        <div class="clearfix"></div>
        @include('orden_trabajo_base_contables.detalles.cruce')
        <div class="clearfix"></div>
    </div>
@endsection


@section('scripts')
    <script>
        $( "[id^='base_contable_']" ).hide();
        function muestraDiv(id){
            $( "[id^='base_contable_']" ).hide();
            $( "#base_contable_" + id ).toggle('slow');
        }

        $(document).ready(function() {
            $("#tbl_excel_1").dataTable( {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                    // "url": "dataTables.german.lang"
                }
            });
        });
    </script>
@append

resources/views/orden_trabajo_base_contables/show_fields.blade.php
<!-- cliente-->

<div class="form-group col-sm-6">
    {!! Form::label('cliente', 'Cliente:') !!}
    <p>{!! $ordenTrabajoBaseContable->ordenTrabajo->cotizacion->cliente->nombre !!}</p>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('num_orden', 'N° de orden de trabajo:') !!}
    <p>{!! $ordenTrabajoBaseContable->ordenTrabajo->num_orden_trabajo !!}</p>

</div>
<div class="clearfix"></div>
<form id="formSubir" name="formSubir" enctype="multipart/form-data" action="{!! url('subir-documento') !!}" method="post">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="orden_trabajo_id" value="{{ $ordenTrabajoBaseContable->orden_trabajo_id }}">
    <div class="col-xs-12 col-lg-12 sinpadding2">
        <div class="custom-upload-file">
            <input
                type="file"
                name="fileImport"
                id="fileImport"
                class="inputfile inputfile-transparent"
                data-multiple-caption="{count} files selected"
            />
            <p class="help-block">Seleccione el archivo a subir.</p>
        </div>
    </div>
    <div class="col-xs-12 col-lg-12 padding-no">
        <div class="col-xs-12 col-lg-6 padding-derecho">
            <input type="submit" class="btn btn-primary">
        </div>
        <div class="col-xs-12 col-lg-6 padding-dizquierdo">
            <!-- <button class="btn_avatar btn_avatar_gris">Cancelar</button> -->
        </div>
    </div>
</form>

<div class="clearfix"></div>


<div class="clearfix"></div>

resources/views/orden_trabajo_base_contables/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection