routes/web.php
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


    Route::resource('areas', 'AreasController');

    Route::resource('empleados', 'EmpleadosController');
    Route::get('getEmpleado/{id}', 'EmpleadosController@getEmpleado');

    Route::resource('puestos', 'PuestosController');

    Route::resource('rubros', 'RubrosController');

    Route::resource('tipoAvaluos', 'TipoAvaluosController');

    Route::resource('tipoCambios', 'TipoCambioController');

    Route::resource('clientes', 'ClienteController');
    Route::get('getClientes', 'ClienteController@getClientes');
    Route::get('getCliente/{id}', 'ClienteController@getCliente');
    Route::resource('clienteRazonSocials', 'ClienteRazonSocialController');

    Route::resource('servicios', 'ServicioController');

    Route::resource('normas', 'NormasController');

    Route::resource('propositoAvaluos', 'PropositoAvaluoController');


    Route::resource('tipoPlaqueos', 'TipoPlaqueoController');

    Route::resource('cotizacions', 'CotizacionController');


    Route::resource('users', 'UserController');


    Route::resource('cotizacionServicios', 'CotizacionServicioController');

    // Route::post('genera-orden/{id}', [
    //     'as' => 'generaOrden',
    //     'uses' =>'CotizacionController@generaOrden'
    // ]);

    Route::resource('ordenTrabajos', 'OrdenTrabajoController');
    Route::get('asignacion-proyecto', 'OrdenTrabajoController@asignacionProyecto');
    Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::get('genera-orden/{cotizacionId}', 'OrdenTrabajoController@generaOrden');

    Route::get('actualiza-asignacion-empleado/{id}', [
        'as' => 'actualizaAsignacionEmpleado',
        'uses' =>'OrdenTrabajoController@actualizaAsignacionEmpleado'
    ]);

    Route::resource('ordenTrabajoRazonSocials', 'OrdenTrabajoRazonSocialController');

    Route::resource('ordenTrabajoBaseContables', 'OrdenTrabajoBaseContableController');

    Route::post('subir-documento', 'OrdenTrabajoBaseContableController@subirDocumento')->name('subirDocumento');


    Route::get('descargar-plantilla/{id}', 'OrdenTrabajoBaseContableController@descargaPlantilla')->name('descargaPlantilla');
    Route::get('descargar-conteo/{id}', 'OrdenTrabajoConteoController@descargaConteo')->name('descargaConteo');
    Route::get('descargar-cruce/{id}', 'OrdenTrabajoBaseContableController@descargaCruce')->name('descargaCruce');

    Route::get('descargar-repetidos-placa_actual/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaActual')->name('descargaRepetidosPlacaActual');
    Route::get('descargar-repetidos-serie/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosSerie')->name('descargaRepetidosSerie');
    Route::get('descargar-repetidos-placa_anterior/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAnterior')->name('descargaRepetidosPlacaAnterior');

    Route::get('descargar-repetidos-placa_auxiliar_1/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar1')->name('descargaRepetidosPlacaAuxiliar1');
    Route::get('descargar-repetidos-placa_auxiliar_2/{id}', 'OrdenTrabajoBaseContableController@descargaRepetidosPlacaAuxiliar2')->name('descargaRepetidosPlacaAuxiliar2');

    Route::resource('ordenTrabajoServicios', 'OrdenTrabajoServicioController');
    Route::resource('ordenTrabajoNormas', 'OrdenTrabajoNormaController');
    Route::resource('ordenTrabajoEmpleados', 'OrdenTrabajoEmpleadoController');


    Route::get('avaluos-antecedentes', [
        'as' => 'avaluos-antecedentes',
        'uses' => 'AvaluoController@antecedentes'
    ]);
    Route::post('avaluos-antecedentes-insert', [
        'as' => 'avaluos-antecedentes-insert',
        'uses' => 'AvaluoDetalleController@insert'
    ]);
    Route::get('avaluos-caracteristicas', [
        'as' => 'avaluos-caracteristicas',
        'uses' => 'AvaluoController@caracteristicas'
    ]);
    Route::get('avaluos-terreno', [
        'as' => 'avaluos-terreno',
        'uses' => 'AvaluoController@terreno'
    ]);
    Route::get('avaluos-descripcion', [
        'as' => 'avaluos-descripcion',
        'uses' => 'AvaluoController@descripcion'
    ]);
    Route::get('avaluos-elementos', [
        'as' => 'avaluos-elementos',
        'uses' => 'AvaluoController@elementos'
    ]);
    Route::get('avaluos-conclusiones', [
        'as' => 'avaluos-conclusiones',
        'uses' => 'AvaluoController@conclusiones'
    ]);

    Route::get('descargar-avaluo/{id}', [
        'as' => 'descargar-avaluo',
        'uses' => 'AvaluoController@descargarAvaluo'
    ]);

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoPropositoAvaluos', 'OrdenTrabajoPropositoAvaluoController');

    Route::resource('ordenTrabajoRubroAlcances', 'OrdenTrabajoRubroAlcanceController');

    Route::resource('ordenTrabajoTipoPlaqueos', 'OrdenTrabajoTipoPlaqueoController');

    Route::resource('ordenTrabajoTipoAvaluos', 'OrdenTrabajoTipoAvaluoController');

    Route::resource('ordenTrabajoDocumentos', 'OrdenTrabajoDocumentoController');
    Route::post('subir-archivo', 'OrdenTrabajoDocumentoController@subirArchivo')->name('subirArchivo');
    Route::post('subir-conteo', 'OrdenTrabajoConteoController@subirConteo')->name('subirConteo');
    Route::resource('ordenTrabajoConteos', 'OrdenTrabajoConteoController');

    Route::get('homologar-columnas/{id}', 'OrdenTrabajoBaseContableController@homologarColumnas')->name('homologarColumnas');

    Route::get('obtener-datos-agrupados/{id}/columna/{columna}', [
        'as' => 'obtenerDatosAgrupados',
        'uses' => 'OrdenTrabajoBaseContableController@obtenerDatosAgrupados'
    ]);

    Route::post('reemplaza-datos-por-columna', [
        'as' => 'reemplazaDatosPorColumna',
        'uses' => 'OrdenTrabajoBaseContableController@reemplazaDatosPorColumna'
    ]);

    Route::resource('civils', 'CivilController');
    Route::resource('civil', 'CivilOrdenesController');

    Route::resource('civilDetalles', 'CivilDetalleController');

    Route::resource('avaluos', 'AvaluoController');
    Route::post('subir-avaluo', 'AvaluoController@subirAvaluo')->name('subirAvaluo');

    Route::resource('avaluoDetalles', 'AvaluoDetalleController');

    Route::resource('ordenTrabajoBaseContableDetalles', 'OrdenTrabajoBaseContableDetalleController');

    Route::resource('archivoMaestros', 'ArchivoMaestroController');

    Route::get('descargar-archivo-maestro/{id}', [
        'as' => 'descargar-archivo-maestro',
        'uses' => 'ArchivoMaestroController@descargarArchivoMaestro'
    ]);

    Route::get('descargar-sobrante-fisico/{id}', [
        'as' => 'descargar-sobrante-fisico',
        'uses' => 'ArchivoMaestroController@descargarSobranteFisico'
    ]);

    Route::get('descargar-sobrante-contable/{id}', [
        'as' => 'descargar-sobrante-contable',
        'uses' => 'ArchivoMaestroController@descargarSobranteContable'
    ]);

    Route::post('subir-archivo-maestro', 'ArchivoMaestroController@subirArchivoMaestro')->name('subirArchivoMaestro');

    Route::resource('archivoMaestroDetalles', 'ArchivoMaestroDetalleController');

    Route::resource('activoFijos', 'ActivoFijoController');

    Route::resource('conciliacions', 'ConciliacionController');
    Route::post('subir-conciliacion', 'ConciliacionController@subirConciliacion')->name('subirConciliacion');
    Route::resource('conciliacionDetalles', 'ConciliacionDetalleController');

    Route::get('descarga-conciliacion', 'ConciliacionController@getConciliacion');

    Route::get('armado-conciliacion', 'AvaluoController@armadoConciliacion');
    Route::get('armado-avaluo', 'ConciliacionController@armadoAvaluo');
    Route::get('armado-conciliacion-avaluo', 'AvaluoController@armadoConciliacionAvaluo');

    Route::get('factura-armado-conciliacion', 'AvaluoController@facturaArmadoConciliacion');
    Route::get('factura-armado-avaluo', 'AvaluoController@facturaArmadoAvaluo');
    Route::get('factura-armado-conciliacion-avaluo', 'AvaluoController@FacturaArmadoConciliacionAvaluo');

    Route::post('subir-factura-armado-conciliacion', 'AvaluoController@subirFacturaArmadoConciliacion')->name('subirFacturaArmadoConciliacion');
    Route::post('subir-factura-armado-avaluo', 'AvaluoController@subirFacturaArmadoAvaluo')->name('subirFacturaArmadoAvaluo');
    Route::post('subir-factura-armado-conciliacion-avaluo', 'AvaluoController@subirFacturaArmadoConciliacionAvaluo')->name('subirFacturaArmadoConciliacionAvaluo');

    // Route::get('asignacion-proyecto-detalle/{ordenTrabajoId}', 'OrdenTrabajoController@asignacionProyectoDetalle');

    Route::resource('fichaTecnicas', 'FichaTecnicaController');
    Route::resource('fichaTecnicaDetalles', 'FichaTecnicaDetalleController');

    Route::resource('placas', 'PlacasController');
    Route::resource('cartas', 'CartasController');
    Route::get('actualizar-carta/{id}', 'CartasController@actualizarCarta')->name('actualizarCarta');
    Route::get('download/{nombre}', 'CartasController@download')->name('descarga.archivo');
    Route::resource('reporteador', 'ReporteadorController');
    Route::get('descargar-reporteador', 'ReporteadorController@download')->name('reporteador.download');
    Route::resource('cuadernillo', 'CuadernilloController');
    Route::get('portada', 'CuadernilloController@portada')->name('cuadernillo.portada');
    Route::get('crear-contenido', 'CuadernilloController@contenidoCrear')->name('cuadernillo.contenido.crear');
    Route::get('crear-contenido-indice', 'CuadernilloController@contenidoCrearIndice')->name('cuadernillo.indice.crear');
    Route::post('crear-indice', 'CuadernilloController@crearIndice')->name('indice.crear');
    Route::get('crear-separador', 'CuadernilloController@separador')->name('cuadernillo.separador');
    

    Route::get('catalogo/{id}', 'CatalogoController@create')->name('catalogo.crear');
});

app/Models/OrdenTrabajoPropositoAvaluo.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use RichanFongdasen\EloquentBlameable\BlameableTrait;

/**
 * Class OrdenTrabajoPropositoAvaluo
 * @package App\Models
 * @version December 5, 2019, 8:02 am CST
 *
 * @property integer orden_trabajo_id
 * @property integer proposito_avaluo_id
 * @property integer blame_id
 */
class OrdenTrabajoPropositoAvaluo extends Model
{
    use SoftDeletes, BlameableTrait;

    public $table = 'ordenes_trabajo_propositos_avaluo';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];
    public $with = ['blame', 'propositoAvaluo'];

    public $fillable = [
        'orden_trabajo_id',
        'proposito_avaluo_id',
        'blame_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'orden_trabajo_id' => 'integer',
        'proposito_avaluo_id' => 'integer',
        'blame_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'orden_trabajo_id' => 'required',
        'proposito_avaluo_id' => 'required'
    ];

    public function blameable()
    {
        return [
            'user' => \App\User::class,
            'createdBy' => 'blame_id',
            'updatedBy' => null,
            'deletedBy' => null
        ];
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function blame()
    {
        return $this->belongsTo(\App\Models\User::class, 'blame_id')->withTrashed();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function propositoAvaluo()
    {
        return $this->belongsTo(\App\Models\PropositoAvaluo::class, 'proposito_avaluo_id')->withTrashed();
    }

}

app/Http/Controllers/OrdenTrabajoPropositoAvaluoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\OrdenTrabajoPropositoAvaluoDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateOrdenTrabajoPropositoAvaluoRequest;
use App\Http\Requests\UpdateOrdenTrabajoPropositoAvaluoRequest;
use App\Repositories\OrdenTrabajoPropositoAvaluoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class OrdenTrabajoPropositoAvaluoController extends AppBaseController
{
    /** @var  OrdenTrabajoPropositoAvaluoRepository */
    private $ordenTrabajoPropositoAvaluoRepository;

    public function __construct(OrdenTrabajoPropositoAvaluoRepository $ordenTrabajoPropositoAvaluoRepo)
    {
        $this->ordenTrabajoPropositoAvaluoRepository = $ordenTrabajoPropositoAvaluoRepo;
    }

    /**
     * Display a listing of the OrdenTrabajoPropositoAvaluo.
     *
     * @param OrdenTrabajoPropositoAvaluoDataTable $ordenTrabajoPropositoAvaluoDataTable
     * @return Response
     */
    public function index(OrdenTrabajoPropositoAvaluoDataTable $ordenTrabajoPropositoAvaluoDataTable)
    {
        return $ordenTrabajoPropositoAvaluoDataTable->render('orden_trabajo_proposito_avaluos.index');
    }

    /**
     * Show the form for creating a new OrdenTrabajoPropositoAvaluo.
     *
     * @return Response
     */
    public function create()
    {
        $propositos = \App\Models\PropositoAvaluo::pluck('nombre', 'id');
        // dd($propositos);
        return view('orden_trabajo_proposito_avaluos.create', compact('propositos'));
    }

    /**
     * Store a newly created OrdenTrabajoPropositoAvaluo in storage.
     *
     * @param CreateOrdenTrabajoPropositoAvaluoRequest $request
     *
     * @return Response
     */
    public function store(CreateOrdenTrabajoPropositoAvaluoRequest $request)
    {
        $input = $request->all();

        $ordenTrabajoPropositoAvaluo = $this->ordenTrabajoPropositoAvaluoRepository->create($input);

        Flash::success('Registro insertado.');

        if (strpos($request->server("HTTP_REFERER"), "pop=1")) {
            return redirect(route('ordenTrabajoPropositoAvaluos.create').'?pop=1&close=1&orden_trabajo_id=0');
        }

        return redirect(route('ordenTrabajoPropositoAvaluos.index'));
    }

    /**
     * Display the specified OrdenTrabajoPropositoAvaluo.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ordenTrabajoPropositoAvaluo = $this->ordenTrabajoPropositoAvaluoRepository->find($id);

        if (empty($ordenTrabajoPropositoAvaluo)) {
            Flash::error('Registro no encontrado.');

            return redirect(route('ordenTrabajoPropositoAvaluos.index'));
        }

        return view('orden_trabajo_proposito_avaluos.show')->with('ordenTrabajoPropositoAvaluo', $ordenTrabajoPropositoAvaluo);
    }

    /**
     * Show the form for editing the specified OrdenTrabajoPropositoAvaluo.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ordenTrabajoPropositoAvaluo = $this->ordenTrabajoPropositoAvaluoRepository->find($id);

        if (empty($ordenTrabajoPropositoAvaluo)) {
            Flash::error('Registro no encontrado.');

            return redirect(route('ordenTrabajoPropositoAvaluos.index'));
        }

        return view('orden_trabajo_proposito_avaluos.edit')->with('ordenTrabajoPropositoAvaluo', $ordenTrabajoPropositoAvaluo);
    }

    /**
     * Update the specified OrdenTrabajoPropositoAvaluo in storage.
     *
     * @param  int              $id
     * @param UpdateOrdenTrabajoPropositoAvaluoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrdenTrabajoPropositoAvaluoRequest $request)
    {
        $ordenTrabajoPropositoAvaluo = $this->ordenTrabajoPropositoAvaluoRepository->find($id);

        if (empty($ordenTrabajoPropositoAvaluo)) {
            Flash::error('Registro no encontrado.');

            return redirect(route('ordenTrabajoPropositoAvaluos.index'));
        }

        $ordenTrabajoPropositoAvaluo = $this->ordenTrabajoPropositoAvaluoRepository->update($request->all(), $id);

        Flash::success('registro actualizado.');

        return redirect(route('ordenTrabajoPropositoAvaluos.index'));
    }

    /**
     * Remove the specified OrdenTrabajoPropositoAvaluo from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ordenTrabajoPropositoAvaluo = $this->ordenTrabajoPropositoAvaluoRepository->find($id);

        if (empty($ordenTrabajoPropositoAvaluo)) {
            Flash::error('Registro no encontrado.');

            return redirect(route('ordenTrabajoPropositoAvaluos.index'));
        }

        $this->ordenTrabajoPropositoAvaluoRepository->delete($id);

        Flash::success('Registro eliminado.');

        return redirect(route('ordenTrabajos.show', ['id' => $ordenTrabajoPropositoAvaluo->orden_trabajo_id]));
        // return redirect(route('ordenTrabajoPropositoAvaluos.index'));
    }
}

resources/views/orden_trabajo_proposito_avaluos/create.blade.php
@extends('layouts.app')

@section('content')
    @if ( isset(session('flash_notification')[0]))
        @php
            $message = session('flash_notification')[0]
        @endphp

        <div class="alta col-md-12">

            <!--COLLAPSER-->
            <div class="col-xs-12 col-md-12 padding-alta">
                <p class="text-alta centers margin-alta">
                    {!! $message['message'] !!}
                </p>
            </div>
            <br />
            <div class="form-group col-sm-12 col-md-12 col-lg-12 padding-tag margin-traspaso">
                <div class="col-xs-12 col-sm-12 col-md-12 margin-validar center-validar margin-10 centers">

                    <button type="button" onclick="closeFancyboxIframe();"
                    class="btn  btn-default" data-dismiss="modal" aria-label="Close">
                        Cerrar
                    </button>

                </div>
            </div>
            <!--COLLAPSER-->
        </div>

    @else
    <section class="content-header">
        <h1>
            Proposito Avaluo
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ordenTrabajoPropositoAvaluos.store']) !!}

                        @include('orden_trabajo_proposito_avaluos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @endif

@endsection

resources/views/orden_trabajo_proposito_avaluos/datatables_actions.blade.php
{!! Form::open(['route' => ['ordenTrabajoPropositoAvaluos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('ordenTrabajoPropositoAvaluos.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('ordenTrabajoPropositoAvaluos.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/orden_trabajo_proposito_avaluos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden Trabajo Proposito Avaluo
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ordenTrabajoPropositoAvaluo, ['route' => ['ordenTrabajoPropositoAvaluos.update', $ordenTrabajoPropositoAvaluo->id], 'method' => 'patch']) !!}

                        @include('orden_trabajo_proposito_avaluos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/orden_trabajo_proposito_avaluos/fields.blade.php
{!! Form::hidden('orden_trabajo_id', app('request')->input('orden_trabajo_id')) !!}
<!-- Orden Trabajo Id Field -->


<!-- Proposito Avaluo Id Field -->


<div class="form-group col-sm-6">
    {!! Form::label('proposito_avaluo_id', 'Proposito Avaluo:') !!}
    {!! Form::select('proposito_avaluo_id', $propositos, null, [
        'class' => 'form-control',
        'id'=>'proposito_avaluo_id',
        'placeholder' => 'Seleccione...'
    ])!!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ordenTrabajoPropositoAvaluos.index') !!}"  onclick="closeFancyboxIframe(); " class="btn btn-default">Cancelar</a>
</div>

resources/views/orden_trabajo_proposito_avaluos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Orden Trabajo Proposito Avaluos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('ordenTrabajoPropositoAvaluos.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('orden_trabajo_proposito_avaluos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/orden_trabajo_proposito_avaluos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden Trabajo Proposito Avaluo
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('orden_trabajo_proposito_avaluos.show_fields')
                    <a href="{!! route('ordenTrabajoPropositoAvaluos.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orden_trabajo_proposito_avaluos/show_fields.blade.php
<!-- Orden Trabajo Id Field -->
<div class="form-group">
    {!! Form::label('orden_trabajo_id', 'Orden Trabajo Id:') !!}
    <p>{!! $ordenTrabajoPropositoAvaluo->orden_trabajo_id !!}</p>
</div>

<!-- Proposito Avaluo Id Field -->
<div class="form-group">
    {!! Form::label('proposito_avaluo_id', 'Proposito Avaluo Id:') !!}
    <p>{!! $ordenTrabajoPropositoAvaluo->proposito_avaluo_id !!}</p>
</div>

<!-- Blame Id Field -->
<div class="form-group">
    {!! Form::label('blame_id', 'Blame Id:') !!}
    <p>{!! $ordenTrabajoPropositoAvaluo->blame_id !!}</p>
</div>

resources/views/orden_trabajo_proposito_avaluos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection